name: Publish to npm

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '24' # Specify your target Node.js version
          cache: 'pnpm'

      - name: Install npm@latest
        run: npm install -g npm@latest

      - name: Check npm version
        run: npm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Publish package
        run: npm publish --provenance